### ISSUE TITLE
Numbers after closing parenthesis

### ISSUE THREAD

**Issue by hmattinson** [dy/parenthesis#6]
Consider the string `'r ((m2 r)4 m3)2'`. This should be parsed as `["r (", ["(", ["m2 r"], ")4 m3"], ")2"]` but is currently parsed as `["r ", [undefined], ""]`. This is due to the interaction of the number with the ID that is added during the parsing process.

**Comment by dy** [comment]
Fixed by #6

**Comment by dy** [comment]
Published in 3.1.6
